OnlineLearning-Client/Controllers/AuthController.cs
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using OnlineLearning_Client.Models;
using Microsoft.AspNetCore.Authentication;
using OnlineLearning_Client.Helper;
using System.Text;
using Newtonsoft.Json;
using OnlineLearning_Client.Services;
using System.Security.Claims;
using System.Net;
using System.Net.Mail;
using System.Net.Http;
using BusinessObject.Utility;
using Microsoft.AspNetCore.Authorization;

namespace OnlineLearning_Client.Controllers
{
    public class AuthController : Controller
    {
        private readonly HttpClient _client;

        [HttpGet]
        public IActionResult ResetPassword()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Verify()
        {
            return View();
        }


        [HttpGet]
        public IActionResult LogOut()
        {
            HttpContext.SignOutAsync("CookieAuthentication");
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(LoginRequest loginRequest)
        {
            try
            {
                var client = new ClientService(HttpContext);
                var requestModel = new LoginRequest { Email = loginRequest.Email, Password = loginRequest.Password };
                var result = await client.PostReturnResponse("/api/Auth/SignIn", requestModel);

                if (result.IsSuccessStatusCode)
                {
                    var content = await result.Content.ReadAsStringAsync();
                    var res = JsonConvert.DeserializeObject<LoginResponseModel>(content);

                    // Set the authentication cookie
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Sid, res.Id.ToString()),
                        new Claim(ClaimTypes.Name, res.FullName),
                        new Claim(ClaimTypes.Email, res.Email),
                        new Claim(ClaimTypes.Role, res.Role)
                    };
                    var claimsIdentity = new ClaimsIdentity(claims, "login");
                    var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                    HttpContext.Response.Cookies.Append("AccessToken", res.Token, new CookieOptions
                    {
                        Expires = DateTime.Now.AddDays(1).AddMinutes(-1)
                    });


                    await HttpContext.SignInAsync("CookieAuthentication", claimsPrincipal,
                        new AuthenticationProperties { IsPersistent = loginRequest.KeepLoggedIn });
                }
                else if (result.StatusCode == HttpStatusCode.BadRequest)
                {
                    TempData["NotificationType"] = "error";
                    TempData["Message"] = "Đăng nhập thất bại, vui lòng thử lại ..";
                    TempData["ShowLoginForm"] = true;
                    TempData["ShowSignupForm"] = false;
                    return RedirectToAction("Index", "Home");
                }

                //TempData["NotificationType"] = "error";
                //TempData["Message"] = "An unexpected error occurred during login.";
            }
            catch (Exception ex)
            {
                // Log the exception for debugging purposes
                //TempData["NotificationType"] = "error";
                //TempData["Message"] = $"An error occurred during login {ex}.";
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpRequest signUpRequest)
        {
            var client = new ClientService(HttpContext);
            var requestModel = new SignUpRequest
            {
                Email = signUpRequest.Email,
                Password = signUpRequest.Password,
                Name = signUpRequest.Name,
                ProfilePicture = "",
                Role = signUpRequest.Role,
            };

            var result = await client.PostReturnResponse("/api/Auth/SignUp", requestModel);

            if (result.IsSuccessStatusCode)
            {
                // SignUp was successful, redirect to SignIn page

                TempData["NotificationType"] = "success";
                TempData["Message"] = "Vui lòng kiểm tra Email của bạn để xác thực tài khoản...";
                TempData["ShowLoginForm"] = true;
                TempData["ShowSignupForm"] = false;
            }
            else if (result.StatusCode == HttpStatusCode.BadRequest)
            {
                // SignUp failed
                TempData["NotificationType"] = "error";
                TempData["Message"] = "Email đã tồn tại trong hệ thống ";
                TempData["ShowLoginForm"] = false;
                TempData["ShowSignupForm"] = true;
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet("ResetPassword")]
        public async Task<IActionResult> ResetPassword(Guid token)
        {
            try
            {
                var client = new ClientService(HttpContext);
                var result = await client.PostReturnResponse("/api/Auth/ResetPassword", token);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return View();
            }
        }


        [HttpPost("ResetPassword")]
        public async Task<IActionResult> ResetPassword(ResetPasswordRequest rq)
        {
            try
            {
                var client = new ClientService(HttpContext);
                var result = await client.PostReturnResponse("/api/Auth/ResetPassword", rq);
                var content = result.Content.ReadAsStringAsync().Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["NotificationType"] = "success";
                    TempData["Message"] = "Đổi mật khẩu thành công...";
                }
                else if (result.StatusCode == HttpStatusCode.BadRequest)
                {
                    TempData["NotificationType"] = "error";
                    TempData["Message"] = content;
                }

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordRequest forgorModel)
        {
            try
            {
                var client = new ClientService(HttpContext);
                var result = await client.PostReturnResponse("/api/Auth/ForgotPassword", forgorModel);

                if (result.IsSuccessStatusCode)
                {
                    // Forgot password request was successful
                    TempData["NotificationType"] = "success";
                    TempData["Message"] = "Vui lòng kiểm tra Email của bạn để đổi mật khẩu mới...";
                    TempData["ShowLoginForm"] = true;
                    TempData["ShowSignupForm"] = false;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    // Forgot password request failed
                    TempData["NotificationType"] = "error";
                    TempData["Message"] = "Có gì đó không đúng vui lòng kiểm tra lại...";
                    TempData["ShowLoginForm"] = true;
                    TempData["ShowSignupForm"] = false;
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                // Log the exception for debugging purposes
                TempData["NotificationType"] = "error";
                TempData["Message"] = $"Có gì đó không đúng vui lòng kiểm tra lại...{ex}";
                TempData["ShowLoginForm"] = false;
                TempData["ShowSignupForm"] = false;
                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = RoleConstant.TEACHER + "," + RoleConstant.STUDENT)]
        public IActionResult MyProfile()
        {
            return View();
        }
    }
}

OnlineLearning-Client/Views/Admin/Dashboard.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <title>Admin Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center; /* Căn giữa theo chiều ngang */
            margin: 0 ;
        }

        .navbar {
            position: relative;
            width: 200px;
            min-height: 100vh;
            background-color: #fffcfc;
            color: #000;
            border-right: 1px solid rgb(231, 228, 228);
        }

            .navbar li:hover {
                background-color: #c7bdbd;
                color: #000;
            }

            .navbar ul {
                list-style-type: none;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-direction: column;
                height: 100%;
                width: 100%;
                padding-left: 0;
            }

            .navbar li {
                width: 100%;
                padding: 10px 0;
                text-align: center;
                cursor: pointer;
                margin-bottom: 10px; /* Thêm khoảng cách dưới */
            }

        .dashboard {
            flex: 1;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center; /* Căn giữa theo chiều ngang */
        }

        .search-bar {
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 20px;
            border-radius: 30px;
            background-color: #f2f2f2;
            padding: 10px;
            width: 50%; /* Giảm kích thước */
        }

            .search-bar input[type="text"] {
                border: none;
                outline: none;
                background: none;
                margin-left: 5px;
                font-size: 16px;
                width: 100%;
            }

        .info-box {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            width: 33.33%; /* Giảm kích thước */
            height: 100px;
            border-radius: 10px;
            background-color: #f2f2f2;
            margin: 7px;
        }

            .info-box strong {
                font-size: 24px;
                font-weight: bold;
            }

            .info-box span {
                font-size: 12px;
            }

        .avatar-box {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 33.33%; /* Giảm kích thước */
        }

        .avatar {
            width: 80px;
            height: 80px;
            border-radius: 50%;
            background-color: #f2f2f2;
        }

            .avatar img {
                width: 100%;
                height: 100%;
                object-fit: cover;
                border-radius: 50%;
            }

        .avatar-name {
            margin-top: 10px;
            font-weight: bold;
        }

        .avatar-count {
            margin-top: 5px;
            font-size: 12px;
        }

        .info-boxes {
            display: flex;
            justify-content: space-between;
            margin-bottom: 50px;
            width: 50%; /* Đẩy rộng khoảng cách giữa info-boxes */

            border-radius: 10px;
            padding: 10px;
        }

        .avatar-boxes {
            display: flex;
            justify-content: space-between;
            margin-bottom: 70px;
            width: 60%; /* Đẩy rộng khoảng cách giữa avatar-boxes */
            border-radius: 10px;
            padding: 10px;
        }

        table {
            width: 50%; /* Đẩy rộng bảng */
            border-collapse: collapse;
            border: 1px solid #ece0e0; /* Thêm border nhạt */
            border-radius: 10px !;
        }

        th,
        td {
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #ccc; /* Thêm border nhạt */
        }

        th {
            background-color: rgb(186, 186, 202);
        }

        td {
            background-color: rgb(252, 250, 250);
        }

        th {
            font-weight: bold;
        }

        .avatar-small {
            width: 20px;
            height: 20px;
            border-radius: 50%;
            background-color: #f2f2f2;
            display: inline-block;
            margin-right: 5px;
        }

            .avatar-small img {
                width: 100%;
                height: 100%;
                object-fit: cover;
                border-radius: 50%;
            }

        .logout-button {
            position: absolute;
            bottom: 0px;
            right: 0px;
            background-color: red;
            color: white;
            padding: 10px;
            text-align: center;
            cursor: pointer;
            font-size: 14px;
        }

            .logout-button i {
                margin-right: 5px;
            }

        .icon-text {
            margin-left: 10px; /* Khoảng cách bên trái của chữ so với icon */
        }
    </style>
</head>
<body>
    <div class="navbar">
        <ul>
            <li>
                <i class="fas fa-book"></i> <span class="icon-text">Lớp học</span>
            </li>
            <li>
                <i class="fas fa-user-graduate"></i>
                <span class="icon-text">Học sinh</span>
            </li>
            <li>
                <i class="fas fa-chalkboard-teacher"></i>
                <span class="icon-text">Giáo viên</span>
            </li>
            <li class="logout-button">
                <i class="fas fa-sign-out-alt"></i>
                <a href="@Url.Action("LogOut", "Auth")" class="icon-text">Logout</a>
            </li>
        </ul>
    </div>

    <div class="dashboard">
        <div class="search-bar">
            <input type="text" placeholder="Tìm kiếm..." />
        </div>

        <div class="info-boxes">
            <div class="info-box">
                <strong>50</strong>
                <span>Lớp học</span>
            </div>
            <div class="info-box">
                <strong>200</strong>
                <span>Học sinh</span>
            </div>
            <div class="info-box">
                <strong>10</strong>
                <span>Giáo viên</span>
            </div>
        </div>

        <div class="avatar-boxes">
            <div class="avatar-box">
                <div class="avatar">
                    <img src="https://png.pngtree.com/png-clipart/20210903/ourmid/pngtree-chemistry-education-subject-shading-png-image_3859086.jpg"
                         alt="" />
                </div>
                <div class="avatar-name">PRN231</div>
                <div class="avatar-count">200 học sinh</div>
            </div>
            <div class="avatar-box">
                <div class="avatar">
                    <img src="https://leerit.com/static/flashcards/words_through_images/tu_vung_tieng_anh_ve_cac_mon_hoc_school_subjects.jpg"
                         alt="" />
                </div>
                <div class="avatar-name">EXE201</div>
                <div class="avatar-count">150 học sinh</div>
            </div>
            <div class="avatar-box">
                <div class="avatar">
                    <img src="https://giasunhantaiviet.com/wp-content/uploads/2022/08/mon-sinh-hoc.jpg"
                         alt="" />
                </div>
                <div class="avatar-name">PRU202</div>
                <div class="avatar-count">10 học sinh</div>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Họ và tên</th>
                    <th>Số điện thoại</th>
                    <th>Số lớp học</th>
                    <th>Số học sinh</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>
                        <div class="avatar-small">
                            <img src="https://www.vietnamworks.com/hrinsider/wp-content/uploads/2023/12/anh-den-ngau.jpeg"
                                 alt="Avatar 1" />
                        </div>
                        Nguyễn Văn A
                    </td>
                    <td>0912345678</td>
                    <td>15</td>
                    <td>1500</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>
                        <div class="avatar-small">
                            <img src="https://haycafe.vn/wp-content/uploads/2021/11/Anh-avatar-dep-chat-lam-hinh-dai-dien.jpg"
                                 alt="Avatar 2" />
                        </div>
                        Trần Thị B
                    </td>
                    <td>0912345678</td>
                    <td>12</td>
                    <td>1300</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>
                        <div class="avatar-small">
                            <img src="https://www.phanmemninja.com/wp-content/uploads/2023/07/anh-dai-dien-zalo-mac-dinh-11.jpg"
                                 alt="Avatar 3" />
                        </div>
                        Lê Văn C
                    </td>
                    <td>0912345678</td>
                    <td>10</td>
                    <td>1200</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>